knp_paginator:
    page_range: 5          # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page    # Nom du paramètre GET pour la page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Template pour la pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'