twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    globals:
        base_template: 'Front_Base.html.twig'

when@test:
    twig:
        strict_variables: true
